CREATE TABLE `NM_USERS` (
    `ID` int(11) NOT NULL AUTO_INCREMENT,
    `USERNAME` varchar(4000) DEFAULT NULL,
    `HASH_PASSWORD` text DEFAULT NULL,
    `FULL_NAME` varchar(255) DEFAULT NULL,
    `IS_ACTIVE` bit(1) DEFAULT NULL,
    `CREATED_BY` varchar(255) DEFAULT NULL,
    `CREATED_ON` datetime(6) DEFAULT NULL,
    `MODIFIED_BY` varchar(255) DEFAULT NULL,
    `MODIFIED_ON` datetime(6) DEFAULT NULL,
    `EMAIL` varchar(255) DEFAULT NULL,
    PRIMARY KEY (`ID`),
    KEY `USERNAME` (`USERNAME`(1024))
);

CREATE TABLE `NM_NOTE` (
    `ID` int(11) NOT NULL AUTO_INCREMENT,
    `USER_ID` int(11) DEFAULT NULL,
    `USERNAME` varchar(255) DEFAULT NULL,
    `SUMMARY` text DEFAULT NULL,
    `CATEGORY` varchar(255) DEFAULT NULL,
    `CREATED_BY` varchar(255) DEFAULT NULL,
    `CREATED_ON` datetime(6) DEFAULT NULL,
    `MODIFIED_BY` varchar(255) DEFAULT NULL,
    `MODIFIED_ON` datetime(6) DEFAULT NULL,
    `IS_ACTIVE` bit(1) DEFAULT NULL,
    `TITLE` varchar(4000) DEFAULT NULL,
    PRIMARY KEY (`ID`),
    KEY `ID` (`ID`),
    KEY `USER_ID` (`USER_ID`)
);

CREATE TABLE `NM_NOTE_SUB_CONTENT` (
    `ID` int(11) NOT NULL AUTO_INCREMENT,
    `NOTE_ID` int(11) DEFAULT NULL,
    `DATA` text DEFAULT NULL,
    `CREATED_BY` varchar(255) DEFAULT NULL,
    `CREATED_ON` datetime(6) DEFAULT NULL,
    `MODIFIED_BY` varchar(255) DEFAULT NULL,
    `MODIFIED_ON` datetime(6) DEFAULT NULL,
    `IS_ACTIVE` bit(1) DEFAULT NULL,
    PRIMARY KEY (`ID`),
    KEY `NOTE_ID` (`NOTE_ID`)
);